settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: myGin
  path: /Users/shiliang/data/vagrant/trusty/dev-go/src/myGin
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
